[Library/Showcase] Create Box tag and unity production page
smartcoop/design-library pull request #104
Opened 2023-07-18 14:33 UTC by NourJammal

# [Library/Showcase]

https://smartjira.atlassian.net/browse/CURU-160

Create Box tag.
Implemented box tag in Unity Production page. (html from this [PR](https://github.com/smartcoop/design-library/pull/91))

https://design-showcase-stage.smartbe.be/Templates/ProductionUnit

💡 Useful resources
https://www.figma.com/proto/Xg7VlIioBRfEGSN72297H4/Account?page-id=1758%3A41786&node-id=1758-41787&viewport=448%2C277%2C0.4&scaling=min-zoom

2023-07-19 12:46 UTC, joe-coop commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
Juste utiliser label plutôt que lable dans l'entièreté du fichier

2023-07-19 12:59 UTC, jad001 commented on src/Smart.Design.Library/Extensions/DependencyRegistration.cs
> +using Smart.Design.Library.TagHelpers.box;
Ce using est il nécessaire, je n'ai trouvé que le répertoire Box dans TagHelpers.

2023-07-19 13:11 UTC, joe-coop commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/ProductionUnit.cshtml
En ligne 96 et 98 les class 3in1 et 3in1__list ne sont pas définies. Peut-être mieux vaudrait utiliser des ids ?

2023-07-19 13:14 UTC, joe-coop commented on src/Smart.Design.Library/Extensions/DependencyRegistration.cs
La ligne 7 est-elle utile ? :-)

2023-07-19 13:15 UTC, joe-coop commented on src/Smart.Design.Library/Extensions/DependencyRegistration.cs
La ligne 7 n'est -elle pas en trop ?

2023-07-20 10:32 UTC, CelineMarique requested changes

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                    <li>The label of title</li>
```suggestion
                    <li>The box title's label</li>
```

OU

```suggestion
                    <li>The label for the box title</li>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                    <li>A sub title (optional)</li>
```suggestion
                    <li>A subtitle (optional)</li>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                    <li>A List for label and value in body of box</li>
```suggestion
                    <li>A Dictionnary of labels and values for the content of the box</li>
```
?

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                    Dictionary<string, string> LabelAndValue = new Dictionary<string, string>
```suggestion
                    Dictionary<string, string> LabelsAndValues = new Dictionary<string, string>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                        "Titulaire: ", "678362 - Marcel Pirnay"
```suggestion
                        "Titulaire: ", "678362 - John Doe"
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                           sub-title="Expérience activités lorem ipsum CDI" label-and-values="@LabelAndValue"></smart-box>
```suggestion
                           sub-title="Expérience activités lorem ipsum CDI" labels-and-values="@LabelsAndValues"></smart-box>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <th>Description</th>
```suggestion
                                <th>Descriptions</th>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>LabelTitle *</td>
```suggestion
                                <td>TitleLabel *</td>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>The label of title</td>
```suggestion
                                <td>The label for the title</td>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>The title</td>
```suggestion
                                <td>The box title</td>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>SubTitle</td>
```suggestion
                                <td>Subtitle</td>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>The sub title</td>
```suggestion
                                <td>The subtitle</td>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>LabelAndValue *</td>
```suggestion
                                <td>LabelsAndValues *</td>
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
> +                                <td>Represents the language menu</td>
Represent the content?

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/ProductionUnit.cshtml
> +﻿@page
Est-ce que ce n'est pas censé être inclu dans le layout général du showcase (il manque en tous cas le retour au reste du site showcase)

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/ProductionUnit.cshtml
> +    string fullNameWithTrigram = "céline Marique (mag)";
```suggestion
    string fullNameWithTrigram = "Jane Doe (doe)";
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/ProductionUnit.cshtml
> +    "Titulaire: ", "678362 - Marcel Pirnay"
```suggestion
    "Titulaire: ", "678362 - John Doe"
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library/Smart.Design.Library.csproj
> +    <Version>1.5.3-pre-released</Version>
On ajoute ce genre de version?

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Box/BoxTagHelper.cs
> +    public Dictionary<string, string> LabelAndValues { get; set; } = new();
```suggestion
    public Dictionary<string, string> LabelsAndValues { get; set; } = new();
```

2023-07-20 10:32 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Box/IBoxHtmlGenerator.cs
> +    /// Generate a list of value from a <see cref="labelAndLinks"/> dictionnary
Si c'est une liste de labels et values, alors peut-être appeler ça labelsAndValues au lieu de valuesAndLinks?

Sinon:

```suggestion
    /// Generate a list of values from a <see cref="labelsAndLinks"/> dictionnary
```

2023-07-20 12:21 UTC, NourJammal commented on src/Smart.Design.Library/Smart.Design.Library.csproj
> +    <Version>1.5.3-pre-released</Version>
Pour testé sur le smart-back-end et si toute es ok on crée la bonne version 1.5.3

2023-07-20 13:48 UTC, CelineMarique approved these changes

2023-07-31 09:17 UTC, merged