hotfix(PAIL-98): [BE - DESIGN] DL - champs téléphone bug
smartcoop/design-library pull request #109
Opened 2023-08-21 07:54 UTC by Nasreddine-Azahaf

# [Library/Showcase]-{PhoneTel}

[JIRA description]([BE - DESIGN] DL - champs "téléphone" bug)

2023-08-23 08:21 UTC, CelineMarique requested changes

2023-08-23 08:21 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml.cs
> +    public string lastName { get; set; }
De manière générale, des majuscules sur les noms de propriété:
LastName, etc.

2023-08-23 08:21 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml.cs
> +    public string sexe { get; set; }
```suggestion
    public string Gender { get; set; }
```

2023-08-23 08:21 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml.cs
> +    public Subscription subscription { get; set; }
```suggestion
    public Subscription Subscription { get; set; }
```

2023-08-23 08:21 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml.cs
>  {
Idem: majuscules

2023-08-23 08:21 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml.cs
> +    public int withholding{ get; set; }
```suggestion
    public double withholding{ get; set; }
```

2023-08-23 08:21 UTC, CelineMarique commented on src/Smart.Design.Library/Smart.Design.Library.csproj
> +    <Version>2.1.1-pre-release</Version>
```suggestion
    <Version>2.1.2</Version>
```

2023-08-24 07:30 UTC, ChMelissa approved these changes

2023-08-24 09:37 UTC, merged