Feature/blip 7894 header not logged with stepper
smartcoop/design-library pull request #143
Opened 2024-03-12 16:12 UTC by marcelpirnay

(https://smartjira.atlassian.net/browse/BLIP-7894)

Change br-componentgroup-footer c-h2 to br-componentgroup-footer c-h4

Adding header documentation and "header not logged in with stepper" documentation

2024-03-12 16:21 UTC, CelineMarique requested changes
- do not remove src/Smart.Design.Library.Showcase.WebApp/Pages/Components/04_todo/Header/NotLoggedInHeader.cshtml, the component is used in unity
- ideally the stepper is a different component from the header and should be used in a content page
- are we sure that the class changes in different components are not going to make a undesire change in unity?

2024-03-19 09:42 UTC, ChMelissa approved these changes
Dans l'idéal, je pense que c'est mieux de faire des PR distinctes quant il y a des améliorations et du développement.

2024-03-21 10:41 UTC, CelineMarique requested changes

2024-03-21 10:41 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
> +        else
Hello, si je comprends bien, toutes les pages publiques auront un stepper avec ces changements. Il sera rajouté si on envoie les paramètres dans l'objet - mais comment du côté Unity on saura quel type d'objet on doit passer en paramètre? 

Aussi, le header public est un layout prend des paramètres globaux en compte, pas des paramètres spécifiques à une page. Donc par exemple, il prends en compte la langue. mais il ne sait pas - lui - s'il va contenir une fiche d'inscription ou un autre type de page. Donc, on ne peut pas lui passer une liste de StepperItems, qui elle n'est connue que quand on arrive dans le controller de la fiche d'inscription.?
C'est pourquoi, il faudrait - me semble-t-il, que le stepper soit indépendant du header.

2024-03-21 10:49 UTC, marcelpirnay commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
> +        else
Et pourquoi ne pas proposer deux versions/layout du header ? le "header-with-stepper“ sera utilisé à l'inscription et le "header-default" sera utilisé pour les autres pages. En fait c'est déjà le cas je pense. Le Header n'est pas le même dans les pages d'entrées (login, inscription) que dans les pages internes.

2024-03-25 23:00 UTC, Nasreddine-Azahaf commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
> +        else
Hello, une implémentation du stepper utilisable hors du header a été faite. Il suffit de téléchargé la version 3.5.0 du nuget package et de copié collé le code la où tu en as besoin. Il y a une version du stepper pour la page d'inscription ainsi qu'une version pour la page de confirmation.

2024-03-26 13:01 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
> +        else
@Nasreddine-Azahaf je n'ai pas de version 3.5.0 du package. La version la plus récente est la 3.4.0. Est-ce celle-là?

2024-03-26 13:13 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
> +                        <div class="c-wizard__label">Données personelles et professionelles</div>
2 n à personnelles

2024-03-27 09:07 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
> +    stepperItems.Add(item2);
création d'une liste pas utilisée?

2024-03-27 09:13 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/INotLoggedInHeaderHtmlGenerator.cs
> +    TagBuilder GenerateNotLoggedInHeader(string homePageUrl, Dictionary<string, string> languagesAndLinks, string? targetLanguage, List<StepperItem>? stepperItems);
Je retirerai ceci de la PR. On ne va pas changer le composant header, cela n'a pas de sens par rapport aux décisions sur les composants DL et télérik

2024-03-27 09:13 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderHtmlGenerator.cs
idem, on ne crée pas un nouveau composant ni charger un composant qu'on utilise déjà

2024-03-27 09:14 UTC, CelineMarique commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
retirer

2024-03-27 09:16 UTC, CelineMarique commented
On a un bloc html qu'on peut copier coller dans unity dans les pages d'exemples et du css qui doit être adapté. Le reste est superflu

2024-03-27 12:54 UTC, Nasreddine-Azahaf commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
> +    stepperItems.Add(item2);
Non, ce sont les vestiges de l'implémentation du stepper intégré au header. Je vais supprimer ca

2024-03-27 12:54 UTC, Nasreddine-Azahaf commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderHtmlGenerator.cs
Idem commentaire précédent

2024-03-27 12:54 UTC, Nasreddine-Azahaf commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
Idem commentaire précédent

2024-03-27 12:55 UTC, Nasreddine-Azahaf commented on src/Smart.Design.Library/TagHelpers/Header/Stepper/StepperItem.cs
Idem commentaire précédent

2024-03-27 13:04 UTC, CelineMarique approved these changes

2024-03-27 13:13 UTC, merged