[Showcase] Improve page subscription
smartcoop/design-library pull request #97
Opened 2023-07-17 18:06 UTC by joe-coop

#  [Showcase] Improve page subscription

[JIRA description](https://smartjira.atlassian.net/browse/pail-80)

* Improve graphical rendering
* add Smart-not-logged-in-header TagHelper

2023-07-18 09:52 UTC, CelineMarique requested changes

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Header/NotLoggedInHeader.cshtml
> +
```suggestion
```

Ce n'est pas utilisé

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Input/Input.cshtml
> +                <h3 class="br-sample-heading c-h3">Text numeric input</h3>
```suggestion
                <h3 class="br-sample-heading c-h3">Numeric input</h3>
```

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Input/Input.cshtml
> +                <p>A standard text input. Use for single numeric value.</p>
```suggestion
                <p>A standard numeric input. Use for single numeric value.</p>
```

Considérer les cas de doubles? ex 11,11 ;)

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Input/Input.cshtml
> +                <pre class="br-sample-markup br-sample-markup-csharp">@("<smart-input-number name=\"InputName\" id=\"textFieldId\" value=\"\" ></<smart-input-number>")</pre>
```suggestion
                <pre class="br-sample-markup br-sample-markup-csharp">@("<smart-input-number name=\"InputName\" id=\"textFieldId\" value=\"\" ></smart-input-number>")</pre>
```

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/RadioButton/RadioButton.cshtml
>              <p><b>Status:</b> Incomplet</p>
```suggestion
            <p><b>Status:</b> Incomplete</p>
```

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/RadioButton/RadioButton.cshtml
> +                <smart-radio name="radioName" id="radioButtonId" label="The label <b>with the possibility to add some html</b>" value="The value" checked="true"></smart-radio>
Nice, mais cela ne s'affiche pas en gras :)

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml
> +                    <li class="c-styleguide-list__item @IsActive("Header")"><a asp-page="../Header/NotLoggedInHeader">Header : Not Logged In</a></li>
De manière générale, pour différencier les deux headers je les nommerais plus ou moins comme ceci (suggestion):
- HeaderBasic `<smart-header-basic>`
- HeaderUserLogged `<smart-header-user-logged>`

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
> +﻿@page
Attention, il a été demandé à @marcelpirnay de changer le design de cette page, entre autres le bouton "envoyer par email" disparaitra...

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                    <div id="blocAnotherAdress" style="display:none;">
Super!!

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                        <smart-input-number id="witholding" name="witholding" value="null"></smart-input-number>
Ah dommage, je peux encore introduire du texte sans que le formulaire m'en empêche
Peut-être aussi, ce serait bien qu'on puisse envoyer un montant en paramètre par défaut depuis le back (une propriété double par exemple, 11,11% - `defaultValue=@defaulDoubleValue`), comme ça il y a déjà un chiffre qui s'affiche dans le input...

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                            <smart-select id="anotherCountry" name="anotherCountry">
```suggestion
                            <smart-select id="anotherCountry" name="anotherCountry" options=@optionList>
```
Nous voudrions pourvoir envoyer la liste depuis le back, car s'il y a un changement de pays (un en plus, ou un chagement de nom, il faut que ça reste dynamique). Donc le smart-select doit créer dynamiquement une liste de balises `<option></option>` selon le paramètre `options`.

Pour info, la liste des pays est récupérée depuis la Db dans le back-end.

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                        </smart-select>
```suggestion
                            <smart-select id="anotherCountry" name="anotherCountry" options=@optionList>
```
Nous voudrions pourvoir envoyer la liste depuis le back, car s'il y a un changement de pays (un en plus, ou un chagement de nom, il faut que ça reste dynamique). Donc le smart-select doit créer dynamiquement une liste de balises `<option></option>` selon le paramètre `options`.

Pour info, la liste des pays est récupérée depuis la Db dans le back-end.

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                        </smart-select>
rajouter un paramètre options au `smart-select`
Voir plus bas commentaire sur le select pays

2023-07-18 09:52 UTC, CelineMarique commented on src/Smart.Design.Library/Extensions/DependencyRegistration.cs
> +            .AddTransient<INotLoggedInHeaderHtmlGenerator, NotLoggedInHeaderHtmlGenerator>();
Voir remarques sur les suggestions noms `HeaderBasic `et `HeaderUserLogged`
Et bien rendre visible le breaking change dans la version du package

2023-07-18 10:53 UTC, NourJammal commented on src/Smart.Design.Library/TagHelpers/Elements/Radio/RadioHtmlGenerator.cs
> +        labelTagBuilder.InnerHtml.AppendHtml("<span>"+label+"</span>");
```suggestion
        labelTagBuilder.InnerHtml.AppendHtml($"<span>{label}</span>");
```

2023-07-18 12:00 UTC, CelineMarique requested changes

2023-07-18 13:33 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
> +﻿@page
On n est pas au courant.

2023-07-18 13:39 UTC, CelineMarique commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
> +﻿@page
Je vous propose alors de sortir cette partie du code de la pull request, ainsi vous n'êtes pas bloqué·es par le retour de Marcel pour finaliser déjà les composants et la page inscription.

2023-07-18 13:39 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Header/NotLoggedInHeader.cshtml
> +
done

2023-07-18 13:40 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/RadioButton/RadioButton.cshtml
>              <p><b>Status:</b> Incomplet</p>
Done.

2023-07-18 13:40 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/RadioButton/RadioButton.cshtml
> +                <smart-radio name="radioName" id="radioButtonId" label="The label <b>with the possibility to add some html</b>" value="The value" checked="true"></smart-radio>
Done.

2023-07-18 13:41 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                        <smart-input-number id="witholding" name="witholding" value="null"></smart-input-number>
Done.

2023-07-18 13:42 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                            <smart-select id="anotherCountry" name="anotherCountry">
Done.

2023-07-18 13:42 UTC, jad001 commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
> +                        </smart-select>
Done.

2023-07-18 13:45 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Elements/Input/IInputHtmlGenerator.cs
> +    /// Generates an &lt;input[type='tel']&gt; compliant with Smart design.
Done.

2023-07-18 13:46 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Elements/Input/InputDateTagHelper.cs
> +/// <see cref="ITagHelper" /> implementation of the Smart design &lt;input&gt; with <c>asp-for</c>, <c>placeholder</c>, <c>value</c> attributes.
Done.

2023-07-18 13:48 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Elements/Input/InputEmailTagHelper.cs
> +/// <see cref="ITagHelper" /> implementation of the Smart design &lt;input&gt; with <c>asp-for</c>, <c>placeholder</c>, <c>value</c> attributes.
Done.

2023-07-18 14:10 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Elements/Input/InputTelTagHelper.cs
> +    /// HTML placeboder of the value of the Input.
Done.

2023-07-18 14:11 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Elements/Select/SelectTagHelper.cs
> +    /// Get or sets the <see cref="Microsoft.AspNetCore.Mvc.Rendering.ViewContext"/> of the executing view.
Done.

2023-07-18 14:14 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderHtmlGenerator.cs
> +
Done.

2023-07-18 14:16 UTC, jad001 commented on src/Smart.Design.Library/TagHelpers/Header/NotLoggedInHeader/NotLoggedInHeaderTagHelper.cs
> +
Done.

2023-07-19 09:08 UTC, joe-coop commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Input/Input.cshtml
> +                <p>A standard text input. Use for single numeric value.</p>
smart-input-number permet l'utilisation d'un nombre fractionnaire comme 11,11 sous forme de double

2023-07-19 09:11 UTC, joe-coop commented on src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml
> +                    <li class="c-styleguide-list__item @IsActive("Header")"><a asp-page="../Header/NotLoggedInHeader">Header : Not Logged In</a></li>
Cette nomenclature est certes plus élégante, mais impliquerait de changer CFA et Unity avec les nouveaux noms, ce qui nous sort pas de mal de notre scoop. On prend le point pour une amélioration future.

2023-07-19 09:12 UTC, joe-coop commented on src/Smart.Design.Library/Extensions/DependencyRegistration.cs
> +            .AddTransient<INotLoggedInHeaderHtmlGenerator, NotLoggedInHeaderHtmlGenerator>();
Pour les noms voir commentaire plus haut.
Pour le breaking change son détail se trouve dans la page ChangeLog

2023-07-19 09:14 UTC, joe-coop commented on src/Smart.Design.Library/TagHelpers/Constants/TagNames.cs
> +    public const string InputTelName = "smart-input-phone";
On préfère garder InputTelName ici car en HTML il est bien de la forme <input type="tel"></input>

2023-07-19 09:15 UTC, joe-coop commented on src/Smart.Design.Library/TagHelpers/Elements/Input/IInputHtmlGenerator.cs
> +    TagBuilder GenerateInputTel(
voir remarque plus haut

2023-07-19 09:18 UTC, joe-coop commented on src/Smart.Design.Library/TagHelpers/Elements/Input/InputNumberTagHelper.cs
> +
Done

2023-09-28 12:39 UTC, closed without merging